--- 
desktop:
  user_before_login: ""
general:
  app_title: Thetis
  default_page: "/thetis/desktop/show"
  default_topicbox: "1"
  header_menus: []
  symbol_title: "Replace Me!"
log:
  max_num: "1000"
menu:
  disp_equipment: "1"
  disp_mail: "1"
  disp_addressbook: "0"
  disp_paintmail: "0"
  disp_research: "1"
  disp_user_list: "1"
  disp_workflow: "1"
  disp_timecard: "1"
  open_user_reg: "0"
  req_login_desktop: "0"
  req_login_equipment: "0"
  req_login_items: "0"
  req_login_schedules: "0"
feed:
  enabled: "1"
  feed_content: "1"
smtp:
  auth: 
  auth_enabled: "0"
  domain: example.com
  from_address: user@example.com
  password: 
  port: "25"
  server: example.com
  user_name: 
topic:
  caption: ""
user:
  by_full_name: "0"
